#
# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.

nValue = int(input("Insert the number of terms: "))
nSum = 0
n1 = 0
fib = 1
i = 0

while i < nValue:
    print(fib)
    fib += n1
    n1 = fib - n1
    i += 1
    if fib % 2 == 0:
        nSum += fib


print(nSum)
